//! Project scaffolding and management

use crate::config::ProjectConfig;
use crate::error::ForgeKitError;
use std::path::Path;
use tokio::fs;

/// Initialize a new project at the given path
pub async fn init(name: &str, path: &Path) -> Result<(), ForgeKitError> {
    tracing::info!("Initializing new project '{}' at {:?}", name, path);
    
    // Check if directory exists
    if path.exists() {
        return Err(ForgeKitError::ProjectExists(
            path.to_string_lossy().to_string()
        ));
    }
    
    // Create project directory
    fs::create_dir_all(path).await?;
    
    // Create src directory
    let src_path = path.join("src");
    fs::create_dir_all(&src_path).await?;
    
    // Create assets directory
    let assets_path = path.join("assets");
    fs::create_dir_all(&assets_path).await?;
    
    // Create initial main.rs
    let main_rs_content = generate_main_rs(name);
    fs::write(src_path.join("main.rs"), main_rs_content).await?;
    
    // Create forgekit.toml
    let config = ProjectConfig {
        name: name.to_string(),
        version: "0.1.0".to_string(),
        description: Some(format!("A new .mox app built with ForgeKit")),
        authors: vec![whoami::username()],
        ..Default::default()
    };
    config.save(path.join("forgekit.toml"))?;
    
    // Create .gitignore
    let gitignore_content = generate_gitignore();
    fs::write(path.join(".gitignore"), gitignore_content).await?;
    
    tracing::info!("Project '{}' initialized successfully", name);
    Ok(())
}

/// Generate the main.rs template
fn generate_main_rs(name: &str) -> String {
    format!(
        r#"//! Main entry point for {name}
//!
//! This is a .mox application built with ForgeKit for Ledokoz OS.

fn main() {{
    println!("Hello from {{}}!", "{name}");
    println!("Built with ForgeKit for Ledokoz OS");
}}
"#
    )
}

/// Generate .gitignore content
fn generate_gitignore() -> String {
    r#"# Generated by ForgeKit
target/
**/*.mo
**/*.mox
**/*.log
.DS_Store
Thumbs.db
"#
    .to_string()
}

/// Get current username (fallback implementation)
mod whoami {
    pub fn username() -> String {
        std::env::var("USER")
            .or_else(|_| std::env::var("USERNAME"))
            .unwrap_or_else(|_| "developer".to_string())
    }
}
